### ISSUE TITLE
add libpng to BUILDING_BINUTILS_CYGWIN.md

### ISSUE THREAD

**Issue by RicoP** [zeldaret/oot#1064]
libpng should be added to the list of required libraries at https://github.com/zeldaret/oot/blob/master/docs/BUILDING_BINUTILS_CYGWIN.md

Otherwise make setup will fail

**Comment by Dragorn421** [comment]
That file provides instructions to build mips-linux-binutils, as its name and header suggest, not to set up the repo.

libpng (libpng-devel I assume) is mentioned in the readme already, under: https://github.com/zeldaret/oot#Cygwin
