### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by JonatasCopernico** [zeldaret/oot#1070]
Just downloaded the code and really wanted to try it, but, i am getting the following error when running "make":
Ambient: windows with Ubuntu WSL
```python3 tools/asm_processor/build.py tools/ido_recomp/linux/7.1/cc -- mips-linux-gnu-as -march=vr4300 -32 -Iinclude -- -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -I. -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -o build/assets/text/nes_message_data_static.o assets/text/nes_message_data_static.c
cfe: Warning 594: o in #if or #elif
3.8
unknown command line option
cfe: Warning 594: o in #if or #elif
3.8
unknown command line option
cfe: Warning 596:
include/message_data_fmt.h: 135: Unterminated string or character constant
A pr
cfe: libc_impl.c:602: wrapper_sprintf: Assertion `0 && "non-implemented sprintf format"' failed.
Fatal error in: /usr/lib/cfe  child died due to signal 6.
Fatal error in: /usr/lib/cfe  Signal 6
Failed to compile file assets/text/nes_message_data_static.c. Command line:

tools/ido_recomp/linux/7.1/cc -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -I. -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -I '/mnt/c/Users/Jonatas Copernico/Desktop/Jhonny/oot/assets/text' -o build/assets/text/nes_message_data_static.o /tmp/preprocessed9wcfmqm4.c
Makefile:234: recipe for target 'build/assets/text/nes_message_data_static.o' failed
make: *** [build/assets/text/nes_message_data_static.o] Error 55```

**Comment by AngheloAlf** [comment]
Did you run `make setup` first?
Please follow the instructions in the readme very carefully
https://github.com/zeldaret/oot#linux-native-or-under-wsl--vm

**Comment by JonatasCopernico** [comment]
yep, runned make setup and followed the readme instructions... And wow, that was fast lol. Thanks

**Comment by AngheloAlf** [comment]
In that case, then this sounds like a problem with line endings.
This usually is caused by cloning with Windows and then using Linux for building (messing up the line endings) I suggest to reclone using Linux
Also, I suggest you to come to the Discord server if you need more help with this, Github issues is not really the best place to discuss this kind of problem

**Comment by iMonZ** [comment]
> In that case, then this sounds like a problem with line endings.
> This usually is caused by cloning with Windows and then using Linux for building (messing up the line endings) I suggest to reclone using Linux
> Also, I suggest you to come to the Discord server if you need more help with this, Github issues is not really the best place to discuss this kind of problem

Could you enable GitHub discussions? Would me much easier!
