### ISSUE TITLE
MacOS compilation

### ISSUE THREAD

**Issue by nlarcipretti** [zeldaret/oot#1090]
Hi!

I've been trying to compile the project in MacOS (monterrey) and after a few bumps on the road I've stumbled into the following error:

```
...
mips-linux-gnu-objcopy -I binary -O elf32-big baserom/zoora_scene build/baserom/zoora_scene.o
tools/mkldscript build/spec build/ldscript.txt
cpp -P -xc++ undefined_syms.txt > build/undefined_syms.txt
mips-linux-gnu-ld -T build/undefined_syms.txt -T build/ldscript.txt --no-check-sections --accept-unknown-input-arch --emit-relocs -Map build/z64.map -o zelda_ocarina_mq_dbg.elf
mips-linux-gnu-ld: não foi possível localizar build/data/unk_80009410.data.o
gmake: *** [Makefile:178: zelda_ocarina_mq_dbg.elf] Error 1
gmake  1335,72s user 379,11s system 82% cpu 34:42,44 total
```

Do you have any idea what could be wrong? I'm new to the ROM compiling world.

Also, is there any reliable place to download the Master debug ROM? I've got mine from a quite shady website...

Thanks

**Comment by Dragorn421** [comment]
Hello, I suggest you join the Discord (link in the readme), it's easier to communicate there

We don't discuss getting ROMs.
