### ISSUE TITLE
Environment_Update in z_kankyo passes arg to void func_800AA16C(void)

### ISSUE THREAD

**Issue by mzxrules** [zeldaret/oot#1129]
See here:

https://github.com/zeldaret/oot/blob/master/src/code/z_kankyo.c#L850

https://github.com/zeldaret/oot/blob/master/src/code/code_800A9F30.c#L85

**Comment by petrie911** [comment]
Probably works fine to remove the argument. globalCtx is likely still in $a0 from the function call.

**Comment by Dragorn421** [comment]
#1148 :
https://github.com/zeldaret/oot/blob/2447a90a55a2771151fe19de346f500440aa5099/src/code/z_kankyo.c#L851
