### ISSUE TITLE
Can't build due to Segmentation Fault

### ISSUE THREAD

**Issue by ryu-ketsueki** [zeldaret/oot#1182]
I was reading this output and at first I thought it may have been a problem with libbfd library because it is a slightly newer version than the one the make file is looking for, more specifically being 2.38 instead of 2.30 but I'm not sure if this is just a warning about the header being a different size than expected or the cause of the problem. Here is the output:
```
python3 tools/asm_processor/build.py tools/ido_recomp/linux/7.1/cc -- mips-linux-gnu-as -march=vr4300 -32 -Iinclude -- -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -I. -Wab,-r4300_mul -woff 649,838,712  -mips2 -O2 -o build/assets/text/nes_message_data_static.o assets/text/nes_message_data_static.c
mips-linux-gnu-objcopy -O binary build/assets/text/nes_message_data_static.o build/assets/text/nes_message_data_static.o.bin
mips-linux-gnu-objcopy: Symbol `_bfd_std_section' has different size in shared object, consider re-linking
mips-linux-gnu-objcopymake: *** [Makefile:309: build/assets/text/nes_message_data_static.o] Segmentation fault (core dumped)
make: *** Deleting file 'build/assets/text/nes_message_data_static.o'
```
If that is so, then I have a problem with the dependency listed on Ubuntu bionic beaver, which is not even the latest LTS but it is the correct version for mips. If it is not and the problem was on that line of make file, how can that be solved?

**Comment by Dragorn421** [comment]
Consider joining the discord (link in the readme or on the website) to discuss more efficiently, though idk if we can help because this is never-seen-before or at least uncommon afaik

If it's specifically this objcopy command that causes issues you could try just removing it, it's not necessary for building. Try to remove this line: https://github.com/zeldaret/oot/blob/93096a45b61cc872b1ea482feb9753daa8f2b069/Makefile#L309

But this crash may just indicate the .o is messed up, and then it would likely fail later when linking I guess. No clue what happened to the .o then. Try fully rebuilding? `make distclean`, `make setup`, `make`

**Comment by ryu-ketsueki** [comment]
Yeah, I did erase that line and now another problem arised, this time with line 294. It keeps mentioning the headers, just like the previous one:
```
mips-linux-gnu-as -march=vr4300 -32 -Iinclude asm/bcmp.s -o build/asm/bcmp.o
mips-linux-gnu-as: Symbol `mips_builtin_opcodes' has different size in shared object, consider re-linking
mips-linux-gnu-as: Symbol `_bfd_std_section' has different size in shared object, consider re-linking
Assembler messages:
Internal error (Segmentation fault).
Please report this bug.
make: *** [Makefile:294: build/asm/bcmp.o] Error 1
```
At this point I'm thinking that I can't use the package provided by Ubuntu repositories and instead I need to install a custom one. I'll join the server to see if I can get more help. Thanks

**Comment by Dragorn421** [comment]
For what it's worth the package that comes with my Kubuntu 21.10 distribution works
```
$ apt show binutils-mips-linux-gnu
Package: binutils-mips-linux-gnu
Version: 2.36.1-6ubuntu1cross2.1
Priority: extra
Section: universe/devel
Source: binutils-mipsen (7+c2.1)
Origin: Ubuntu
```

**Comment by ryu-ketsueki** [comment]
> For what it's worth the package that comes with my Kubuntu 21.10 distribution works
> 
> ```
> $ apt show binutils-mips-linux-gnu
> Package: binutils-mips-linux-gnu
> Version: 2.36.1-6ubuntu1cross2.1
> Priority: extra
> Section: universe/devel
> Source: binutils-mipsen (7+c2.1)
> Origin: Ubuntu
> ```

I may need to download that as a deb because I got different repos
