### ISSUE TITLE
step 4 -Make setup 

### ISSUE THREAD

**Issue by himansh-u** [zeldaret/oot#1189]
Error: Expected a hash of f0b7f35375f9cc8ca1b2d59d78e35405 but got e4952ae1cac3a380d7f9cef3c2845dff. The baserom has probably been tampered, find a new one
make: *** [Makefile:250: setup] Error 1

**should I find a new rom and if yes where can I find it that will work suitable?**

**Comment by AngheloAlf** [comment]
As the error message says, yes, you need to find a new one.

We won't share ROMs or point you where to find one. Please don't ask again.

If you have more questions about the build process or how to use the repository, I invite you to join us to the discord server. The invitation link is on the readme of this repository.
