### ISSUE TITLE
Error when compiling a `*_cutscene_data.c`-like file: `Missing ')' in macro instantiation`

### ISSUE THREAD

**Issue by Dragorn421** [zeldaret/oot#1224]
# Typical error message

`Missing ')' in macro instantiation`
when compiling a `.c` file named like `cutscene_data` (or holding any cutscene data, supposedly)

# Cause

Unknown, determined to be a recomp issue through testing.

(recomp refers to a recompilation of the original compiler, IDO, which behaves the same for what matters, and is used instead of emulating the original for speed reasons)

# Fix

Unknown. There are two workarounds though:

## Easy hacky workaround (recommended?): Add whitespace in `z64cutscene_commands.h`

Add whitespace anywhere in the `z64cutscene_commands.h` file (`include/z64cutscene_commands.h`),
maybe above or in the `LIGHTING` macro (`#define CS_LIGHTING(...`)
(*not* after any `\` character or in the middle of a word!)

Save the file and continue building.

(no one knows why exactly this works)

## More proper workaround: Don't use recomp

Emulate original IDO instead of using recomp. This makes building slower. To do so:

1) Download `qemu-irix` from https://github.com/zeldaret/oot/releases/tag/0.1q
2) Place it somewhere, preferably in the WSL filesystem (for example in your home directory `~`)
3) Change the permissions on `qemu-irix` to make it executable (for example `chmod u+x qemu-irix`)
4) Run make with setting `QEMU_IRIX` to the path to your `qemu-irix`, and setting `ORIG_COMPILER` to 1 (for example `make QEMU_IRIX=~/qemu-irix ORIG_COMPILER=1`)

# Typical last logs

People reporting this issue provided the following logs at the end of `make` output when build fails due to this:

<details>

```
Error: src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_1.c:10: Missing ')' in macro instantiation
Failed to compile file src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_1.c. Command line:

tools/ido_recomp/linux/7.1/cc -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -I. -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -I /home/tino/Software/modding/ZELDA/DECOMP/oot/src/overlays/actors/ovl_Bg_Toki_Swd -o build/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_1.o /tmp/preprocessedghhjqh8x.c

make: *** [Makefile:318: build/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_1.o] Error 55
```

```
Error: src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_2.c:92: Missing ')' in macro instantiation
Failed to compile file src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_2.c. Command line:

tools/ido_recomp/linux/7.1/cc -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -I. -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -I /home/tino/Software/modding/ZELDA/DECOMP/oot/src/overlays/actors/ovl_Bg_Toki_Swd -o build/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_2.o /tmp/preprocessed0ioli7w1.c

make: *** [Makefile:318: build/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_2.o] Error 55
```

```
python3 tools/asm_processor/build.py tools/ido_recomp/linux/7.1/cc -- mips-linux-gnu-as -march=vr4300 -32 -Iinclude -- -c  -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -I. -Wab,-r4300_mul -woff 649,838,712  -mips2 -O2 -o build/src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.o src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.c
cfe: Error: src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.c:26: Missing ')' in macro instantiation
cfe: Error: src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.c:26: Missing ')' in macro instantiation
Failed to compile file src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.c. Command line:

tools/ido_recomp/linux/7.1/cc -c -G 0 -non_shared -Xfullwarn -Xcpluscomm -Iinclude -Isrc -Iassets -Ibuild -I. -Wab,-r4300_mul -woff 649,838,712 -mips2 -O2 -I /home/bigwhite/oot/src/overlays/actors/ovl_Demo_Im -o build/src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.o /tmp/preprocessed9eo1owjf.c

Makefile:318: recipe for target 'build/src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.o' failed
make: *** [build/src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.o] Error 55
```

</details>

**Comment by Dragorn421** [comment]
Note: #1272 added an extra line break in `z64cutscene_commands.h` so maybe this issue won't come up anymore for a while

**Comment by fig02** [comment]
this file also changes drastically in the z_demo pr. So it probably wont be an issue for this file specifically.
It may resurface again, and at that point the errors will look different. So will close this for now, and hopefully we wont need to make another lol
