### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [zeldaret/oot#1282]
Cool project!

I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

I suggest AGPL-3.0-or-later because this matches the [fado](https://github.com/zeldaret/oot/blob/master/tools/fado/LICENSE) dependency.  See also the [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins).

CC0 as proposed in https://github.com/zeldaret/oot/pull/1194 does not work because fado is under AGPL and ZAPD is under [MIT](https://github.com/zeldaret/oot/blob/master/tools/ZAPD/LICENSE).  Individual files could be licensed under the CC0-1.0 license, but not the entire repository.

A barrier to this change would be that ido would need to be moved externally from the repository because of their [LICENSE.md](https://github.com/zeldaret/oot/blob/master/tools/ido5.3_compiler/LICENSE.md)

It is also possible that this repository cannot be licensed at all, neither copyright, permissive, or copyleft.  See [issue 347 on pokered](https://github.com/pret/pokered/issues/347).

I am not a lawyer.

**Comment by Dragorn421** [comment]
Hi,

> I see you have no LICENSE file for this project. The default is copyright.

Yes we know about what you tried to express there. (no license = all rights reserved)

It is unclear if we can at all (re)license the game code itself. We know about this licensing issue, but we aren't more lawyers than you.

#1194 doesn't suggest CC0 for the whole repo, see the COPYING file there for details. The plan is to license tools first.

**Comment by garrettjoecox** [comment]
> Hi,
> 
> > I see you have no LICENSE file for this project. The default is copyright.
> 
> Yes we know about what you tried to express there. (no license = all rights reserved)
> 
> It is unclear if we can at all (re)license the game code itself. We know about this licensing issue, but we aren't more lawyers than you.

I'm not sure how much this has been discussed since this issue was closed, but by uploading this code to Github you have already effectively "(re)licensed the game code itself". 

It seems inaction here is actually a worse route than picking one of the more favorable licenses, one that protects contributors and forks of your project. Can this be revisited?

**Comment by bapani** [comment]
This code cannot be licensed because it's derived from a work copyrighted by nintendo, and as such retains said copyright.

**Comment by garrettjoecox** [comment]
> This code cannot be licensed because it's derived from a work copyrighted by nintendo, and as such retains said copyright.

By this logic this repository and all forks of it should be taken down then correct? Quoting from [github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository):
> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

**Comment by luckytyphlosion** [comment]
It's up to Nintendo to issue the DMCA. GitHub doesn't have to do anything as long as it complies with a takedown notice.

**Comment by garrettjoecox** [comment]
> It's up to Nintendo to issue the DMCA. GitHub doesn't have to do anything as long as it complies with a takedown notice, as stated in the [Online Copyright Infringement Liability Limitation Act](https://en.wikipedia.org/wiki/Online_Copyright_Infringement_Liability_Limitation_Act#Knowledge_of_infringing_material). For one reason or another, Nintendo hasn't sent DMCAs to any disassemblies or decompilations. However, other decompilations such as [Cave Story](https://github.com/github/dmca/blob/master/2020/11/2020-11-19-nicalis.md) and [Grand Theft Auto 3](https://github.com/github/dmca/blob/master/2021/02/2021-02-19-take-two.md) have not been so lucky (Some of the GTA3 decomp contributors are currently in a [legal](https://storage.courtlistener.com/recap/gov.uscourts.cand.384429/gov.uscourts.cand.384429.1.0.pdf) [battle](https://github.com/github/dmca/blob/master/2021/09/2021-09-29-take-two-legal-action/2021-09-29-take-two-legal-action.md) with Take Two after they counterclaimed the DMCA).

Well in it's current state it's up to either Nintendo or any single contributor to this repository, due to the nature of the default license it's inherited. So I hope no one that has contributed might eventually want to wreak havoc or wishes ill intent on the project.

**Comment by aMannus** [comment]
> This code cannot be licensed because it's derived from a work copyrighted by nintendo, and as such retains said copyright.

Except putting it on GitHub and not choosing a license is the same as choosing for the default licensing, which is incredibly restrictive and can lead to any contributor of the project to shut down any and all forks of decomp.

There's no such thing as "no license" when the code is already on GitHub.

**Comment by Clownacy** [comment]
> This code cannot be licensed because it's derived from a work copyrighted by nintendo, and as such retains said copyright.

Are you a lawyer? Can you actually prove that this decompilation counts as a derivative work? I could just as easily argue that copyright only applies to creative expression, not functionality, and that this decompilation exists only to replicate the _functionality_ of Ocarina of Time. There's nothing wrong with making a really, really, accurate clone of a popular video game.

We can make baseless claims all day - the only way anything can be decided for certain is in a courtroom.
