### ISSUE TITLE
Incorrect `TextBoxPosition` values in `include/message_data_static.h`?

### ISSUE THREAD

**Issue by leggettc18** [zeldaret/oot#1326]
I noticed that the `TextBoxPosition` enum in `include/message_data_static.h` seems to have `TEXTBOX_POS_MIDDLE` and `TEXTBOX_POS_BOTTOM` flipped around. It has the former as 3 and the latter as 2, which doesn't match with my experience in-game while working on a PC port, or with the information available on [wiki.cloudmodding.com/oot](https://wiki.cloudmodding.com/oot/Text_Format#Text_box_types). The only place these values seem to be referenced is in `src/code/z_message_PAL.c` line 3151, where it seems like it could be placing a message box meant for the middle of the screen down to the bottom instead and vice versa, although I haven't yet found anywhere in game where this actually happens.

I could definitely be missing something, but I haven't been able to figure it out yet.

**Comment by jpburnett** [comment]
There is nothing wrong with the enums, they are correctly named

With `TEXTBOX_POS_MIDDLE`:
![image](https://user-images.githubusercontent.com/20159000/179668441-1557789f-de62-41c5-9d9e-e0ce6bd72106.png)

With `TEXTBOX_POS_BOTTOM`:
![image](https://user-images.githubusercontent.com/20159000/179668600-c27601d9-941c-4969-b939-205258a1db3f.png)

**Comment by leggettc18** [comment]
Well there's definitely something different happening on my end, but I have not been able to figure out what it is. I can't completely rule out that some change on my end is causing it, but comparing codebases I haven't been able to find any differences related to this. I guess I've gotta be doing something wrong though; a `msgCtx->textBoxPos of 3` is definitely going to the bottom for me, but the enum seems to suggest it would be going to the middle. Can you tell me where in the code did you set the position to get those pictures? I've been able to change `font->charTexBuf[0]` to `0x##`, with the first digit being the type and the second digit being the position, and `0x23` puts a blue text box at the bottom for me.

**Comment by mzxrules** [comment]
https://github.com/zeldaret/oot/blob/397e481f9a3eedf2123cc2fc149468a96b473e88/src/code/z_message_PAL.c#L3034-L3042

Yea from this code it looks like middle and bottom should be swapped. I also wrote a test myself and found it to be that 2 is middle, 3 is bottom.
