### ISSUE TITLE
Makefile 67

### ISSUE THREAD

**Issue by Huntedkitty** [zeldaret/oot#1516]
make -s
Makefile:67: *** Unable to find mips-linux-gnu-ld. Please install or build MIPS binutils, commonly mips-linux-gnu. (or set MIPS_BINUTILS_PREFIX if your MIPS binutils install uses another prefix).  Stop.
exit status 2

**Comment by Huntedkitty** [comment]
anybody know what that means?

**Comment by Dragorn421** [comment]
Hello
Please follow the instructions here to build this project: https://github.com/zeldaret/oot#installation

**Comment by Dragorn421** [comment]
Inactive, closing

**Comment by Pysis868** [comment]
Had this problem with Fedora.
Alias function did not help, as it was not detected, but a file/symlink or env var did.

`ln -s /usr/bin/mips64-linux-gnu-ld ~/bin/mips-linux-gnu-ld;`
or
`env MIPS_BINUTILS_PREFIX='mips64-linux-gnu-' VERSION='gc-us-mq' make setup;`

```
binutils-mips64-elf-2.43.1-1.fc41.x86_64
binutils-mips64-linux-gnu-2.43.1-2.fc41.x86_64
gcc-c++-mips64-elf-14.2.0-1.fc41.x86_64
gcc-c++-mips64-linux-gnu-14.2.1-2.fc41.x86_64
gcc-mips64-elf-14.2.0-1.fc41.x86_64
gcc-mips64-linux-gnu-14.2.1-2.fc41.x86_64
```
