### ISSUE TITLE
Nonmatching build on mips64-elf

### ISSUE THREAD

**Issue by ProjectRevoTPP** [zeldaret/oot#203]
Using mips64-elf results in a nonmatching ROM.

The cause is the . = ALIGN(0x10) in mkldscript.c. With these, the linker inserts extra 00s for some reason where it isnt necessary. Removing these results in OK.

**Comment by ethteck** [comment]
I see seven times this gets done in mkldscript.c, unfortunately. Do you have to remove all of them for OK only a subset? @ProjectRevoTPP 

My compulsion to not have issues open makes me want to fix this, but I'm also not sure how important it is in the grand scheme.

**Comment by sorenbug** [comment]
Just ran into this issue myself on Arch Linux. I removed all instances of `. = ALIGN(0x10)` in `tools/mkldscript.c`, and I still ran into extra zeroes:

```
[soren@hydrogen oot]$ cmp -l baserom.z64 zelda_ocarina_mq_dbg.z64 | gawk '{printf "%08X %02X %02X\n", $1-1, strtonum(0$2), strtonum(0$3)}' | head
00000000 80 00
00000001 37 00
00000002 12 00
00000003 40 00
00000007 0F 00
00000009 00 37
0000000A 04 12
0000000B 00 40
0000000E 14 00
0000000F 4C 0F
[soren@hydrogen oot]$ hexdump baserom.z64 | head
0000000 3780 4012 0000 0f00 0080 0004 0000 4c14
0000010 7d91 f618 bc69 5354 0000 0000 0000 0000
0000020 4854 2045 454c 4547 444e 4f20 2046 455a
0000030 444c 2041 0000 0000 0000 4e00 4c5a 0f50
0000040 a003 2048 288d 10f0 6a8d 4400 4801 2650
0000050 2aad 10f0 6b21 0400 0831 ff0f 0015 f9ff
0000060 2921 0400 688d 4400 6a8d 4800 28ad 10f0
0000070 2aad 14f0 e007 1000 20ad 18f0 0000 0000
0000080 0000 0000 1c7c c097 889b 02f8 bc05 e016
0000090 9971 8000 1175 14fe 9c7c c0b7 39cd 2410
[soren@hydrogen oot]$ hexdump zelda_ocarina_mq_dbg.z64 | head
0000000 0000 0000 0000 0000 3780 4012 0000 0f00
0000010 7d91 f618 11b2 fbde 7d91 f618 bc69 5354
0000020 0000 0000 0000 0000 4854 2045 454c 4547
0000030 444e 4f20 2046 455a 444c 2041 0000 0000
0000040 0000 4e00 4c5a 0f50 a003 2048 288d 10f0
0000050 6a8d 4400 4801 2650 2aad 10f0 6b21 0400
0000060 0831 ff0f 0015 f9ff 2921 0400 688d 4400
0000070 6a8d 4800 28ad 10f0 2aad 14f0 e007 1000
0000080 20ad 18f0 0000 0000 0000 0000 1c7c c097
0000090 889b 02f8 bc05 e016 9971 8000 1175 14fe
```

**Comment by ethteck** [comment]
Interesting, thanks for the info! Is this a blocker for you (meaning you can't use mips-linux-gnu)?

**Comment by sorenbug** [comment]
I have `mips64-linux-gnu-binutils` installed. Should I change my prefix to use them?

**Comment by ethteck** [comment]
Interesting...do you have discord? You can ping me (@Ethan) if you want to troubleshoot this more rapidly.

**Comment by ethteck** [comment]
After discussing this a bit more in discord, I think we should officially remove mips64-elf from the Makefile and make it a bit more clear that one needs mips-linux-gnu-binutils specifically.

We should also provide some sort of loose instructions for building these manually, since it's necessary on some distros that don't have this in their package managers. Thoughts?

**Comment by sorenbug** [comment]
So, the fix on Arch Linux: `build-essential` -> `base-devel`, and to get `mips-linux-gnu-binutils` currently you download the latest version of `binutils` and `./configure --target=mips-linux-gnu`.

I'm planning on making an AUR package to handle the second step automatically.

**Comment by nanaian** [comment]
@sorenbug Just published [mips-linux-gnu-binutils](https://aur.archlinux.org/packages/mips-linux-gnu-binutils/) on the AUR.

**Comment by ethteck** [comment]
In #316 we removed references to other binutils from the repo, and now that there's an easier way to set up mips-linux-gnu-binutils on arch, I think this issue can be closed.
