### ISSUE TITLE
The discord invite is dead

### ISSUE THREAD

**Issue by palladidrago** [zeldaret/oot#408]
inv is dead

**Comment by Dragorn421** [comment]
Doesn't seem to be. What link are you using?
(don't hesitate about putting more efforts into your sentences)

**Comment by Kenix3** [comment]
Can you try using the invite at https://discord.zelda64.dev/

**Comment by palladidrago** [comment]
it works thanks

> 
> 
> Can you try using the invite at https://discord.zelda64.dev/
