### ISSUE TITLE
make setup crashes on low-end pcs

### ISSUE THREAD

**Issue by shawlucas** [zeldaret/oot#597]
Make setup crashes on low-end pcs, or significantly slows the pc down because of the recent addition of the -j flag. Maybe we can either remove -j, or make it so it does something like -j(Number of cpu cores) because -j without any number makes it run unlimited which crashes on low-end pcs (both my laptop and my desktop, as they are quite old)

**Comment by ethteck** [comment]
Presumably, make setup should pass the -j value passed in via the command line instead of using whatever it wants.
`make setup` (no -j)
`make setup -j` (pass -j)
`make setup -j4` (pass -j4)

**Comment by shawlucas** [comment]
It also passes -j no matter what. I think that should be changed

**Comment by fig02** [comment]
https://github.com/zeldaret/oot/pull/804
