### ISSUE TITLE
Why does this exist?

### ISSUE THREAD

**Issue by iMonZ** [zeldaret/oot#725]
Why does this tutorial exist: https://github.com/zeldaret/oot/blob/master/docs/BUILDING_BINUTILS_MACOS.md

You can just run:
`brew install binutils`

What is the difference from compiling it yourself?

**Comment by ethteck** [comment]
That `binutils` package is standard binutils, not mips-linux-binutils. We need a mips cross toolchain to assemble the rom: see the [Makefile ](https://github.com/zeldaret/oot/blob/master/Makefile#L59) for more context.

**Comment by iMonZ** [comment]
> That `binutils` package is standard binutils, not mips-linux-binutils. We need a mips cross toolchain to assemble the rom: see the [Makefile ](https://github.com/zeldaret/oot/blob/master/Makefile#L59) for more context.

All right now I see that.
I thought the brew pack downloads the same package so whats the difference but this explains this error message 
Makefile:41: *** Please install or build mips-linux-gnu.  Stop.
