### ISSUE TITLE
Confusion about which version of the game is needed for building. 

### ISSUE THREAD

**Issue by lividhen** [zeldaret/oot#944]
For the currently supported master quest build, do you need the master quest version of the game? Or can you use the original game, which is far easier to legally obtain (being that it  is on the Wii U as a virtual console game and is available to purchase digitally).

**Comment by Dragorn421** [comment]
Yes we are using a master quest debug rom as the base rom (the one with md5 `f0b7f35375f9cc8ca1b2d59d78e35405` as mentioned in the readme)

Feel free to join the Discord server to chat (the link is in the [readme](https://github.com/zeldaret/oot/blob/master/README.md))

**Comment by fig02** [comment]
closing issue. if you have any more questions, the discord is probably a better place to ask
